/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One Arrow `RecordBatch` of query output.
 *
 * Data leaves via `toIPC()` (one copy; rehydrate with `apache-arrow`'s
 * `tableFromIPC`) or `toArray()` (row objects). The batch is immutable.
 */
export declare class ArrowBatch {
  numRows(): number
  numColumns(): number
  schema(): Array<FieldInfo>
  /** This batch as an Arrow IPC stream `Buffer` (schema included). */
  toIPC(): Buffer
  /**
   * Row objects (one per row, keyed by column); see `conversion` for the
   * type conventions and the supported-type set.
   */
  toArray(): Array<object>
}

export declare class Connection {
  /**
   * Execute one SQL statement. `SELECT` returns `kind: "query"` with the
   * fully collected `result`; SHOW/DESCRIBE return `kind: "metadata"` with
   * their batch; DDL and `INSERT INTO` return their statement outcome.
   * Fails with `LAMINAR_101` after `close()`.
   */
  execute(sql: string): Promise<ExecuteOutcome>
  /**
   * Execute a query and return its fully collected result. Non-query SQL
   * rejects with `LAMINAR_400`.
   */
  query(sql: string): Promise<QueryResult>
  /**
   * Ingest JS row objects into a source (one batch; returns rows pushed).
   *
   * Sync by design: no engine await is involved (schema resolve → convert →
   * channel send) and the row conversion needs the JS `Env`, which is only
   * valid on the calling turn.
   */
  insert(source: string, rows: Array<object>): number
  /** Ingest an Arrow IPC stream `Buffer` into a source (all batches). */
  insertArrow(source: string, bytes: Buffer): number
  /**
   * Open a streaming writer for a source. Single-owner; writes after
   * `close()` reject with `LAMINAR_301`.
   */
  writer(source: string): Writer
  /** Start the streaming pipeline (idempotent). */
  start(): Promise<void>
  /**
   * Trigger a manual checkpoint. Rejects when checkpointing is not
   * configured (`checkpoint` in the open config), when no pipeline
   * topology exists (at least one stream or sink must be defined — the
   * core wires the coordinator only then), or when the attempt fails.
   */
  checkpoint(): Promise<CheckpointOutcome>
  /** True when checkpointing is configured for this connection. */
  isCheckpointEnabled(): boolean
  /** Registered source names. */
  listSources(): Promise<Array<string>>
  /** Registered stream names. */
  listStreams(): Promise<Array<string>>
  /** Registered sink names. */
  listSinks(): Promise<Array<string>>
  /** All registered sources with schemas and watermark columns. */
  sourceInfos(): Promise<Array<SourceInfoObject>>
  /** Schema of a source as field info; unknown names reject `LAMINAR_200`. */
  schema(name: string): Promise<Array<FieldInfo>>
  /**
   * Subscribe to a named stream or materialized view (pull style):
   * `nextFrame()` per frame, terminal failures reject once (502 lag /
   * 500 otherwise). Frames already queued when `cancel()` fires are
   * drained first, then the next call resolves `null`. `filter` is an
   * optional SQL row filter; `fromEpoch` replays entries after that
   * committed checkpoint epoch (rejects if unretained). Bare sources are
   * not subscribable (core rule, surfaces as `LAMINAR_200`).
   */
  subscribe(name: string, filter?: string | undefined | null, fromEpoch?: number | undefined | null): Promise<Subscription>
  /**
   * Subscribe push style: frames are delivered to `onData(frame)` one at
   * a time, and the reader awaits each delivery's returned promise — a
   * slow handler backpressures the stream (the TypeScript facade makes
   * sync handlers behave identically). `onError(error)` fires once on
   * terminal failures or handler rejections, always followed by exactly
   * one `onClose()`; open failures surface the same way. Callbacks never
   * fire after `close()` resolves (the first caller waits for the reader;
   * a concurrent second caller may resolve marginally earlier).
   */
  subscribeWith(name: string, filter: string | undefined | null, fromEpoch: number | undefined | null, onData: (frame: SubscriptionFrame) => Promise<void>, onError: (error: CallbackError) => void, onClose: () => void): PushSubscription
  /**
   * Execute a query and stream its batches on demand instead of
   * collecting; non-query SQL rejects with `LAMINAR_400`.
   */
  streamQuery(sql: string): Promise<QueryStream>
  /**
   * Cancel a query by the id reported by `streamQuery().queryId`;
   * unknown ids reject.
   */
  cancelQuery(queryId: number): Promise<void>
  /** Aggregate pipeline counters. */
  metrics(): Promise<PipelineMetricsObject>
  /** Counters for one source; unknown names reject `LAMINAR_200`. */
  sourceMetrics(name: string): Promise<SourceMetricsObject>
  /** Counters for every source. */
  allSourceMetrics(): Promise<Array<SourceMetricsObject>>
  /** Counters for one stream; unknown names reject `LAMINAR_200`. */
  streamMetrics(name: string): Promise<StreamMetricsObject>
  /** Counters for every stream. */
  allStreamMetrics(): Promise<Array<StreamMetricsObject>>
  /** Engine lifecycle state name. */
  pipelineState(): Promise<string>
  /** Minimum event-time watermark across sources (epoch milliseconds). */
  pipelineWatermark(): Promise<number>
  /** Total events the pipeline has processed. */
  totalEventsProcessed(): Promise<number>
  isClosed(): boolean
  /**
   * Close the connection: graceful engine shutdown. The first caller
   * performs the shutdown; concurrent callers wait out that attempt as
   * no-ops. A *failed* shutdown (e.g. the core's internal 45 s deadline)
   * rejects and un-latches the connection so `close()` can be retried —
   * idempotent close means converged-to-closed, not one-shot. Using the
   * connection after a successful close fails with `LAMINAR_101`.
   */
  close(): Promise<void>
}

/**
 * One executed statement's outcome, discriminated by the `kind` getter:
 * `ddl` | `rows-affected` | `query` | `metadata`.
 *
 * `query` and `metadata` outcomes carry the fully collected `result()`;
 * `ddl` and `rows-affected` carry their statement information.
 */
export declare class ExecuteOutcome {
  get kind(): string
  /** DDL statement type (e.g. `"CREATE SOURCE"`); `undefined` otherwise. */
  get statementType(): string | null
  /** DDL object name; `undefined` otherwise. */
  get objectName(): string | null
  get rowsAffected(): number | null
  get queryId(): number | null
  /**
   * The collected result for `query`/`metadata` outcomes; `undefined`
   * for `ddl`/`rows-affected`.
   */
  get result(): QueryResult | null
}

/**
 * A push-based subscription: frames are delivered to `onData` one at a time
 * (each delivery is awaited, so a slow consumer applies backpressure
 * instead of growing a queue). `close()` stops delivery and resolves only
 * after the reader has stopped — no callbacks fire after it returns.
 */
export declare class PushSubscription {
  isActive(): boolean
  /**
   * Stop delivery and wait for the reader to finish. Idempotent; the
   * first caller performs the wait.
   */
  close(): Promise<void>
}

/** A fully collected query result: schema plus all output batches. */
export declare class QueryResult {
  schema(): Array<FieldInfo>
  numRows(): number
  numBatches(): number
  /** Batch `index` (0-based); rejects with 400 when out of range. */
  batch(index: number): ArrowBatch
  /** The whole result as one Arrow IPC stream `Buffer` (schema included). */
  toIPC(): Buffer
  /** All rows as objects, batch order preserved. */
  toArray(): Array<object>
}

/**
 * A streaming query: batches arrive on demand instead of one collected
 * result (plan 03 Task 2.3).
 *
 * `nextBatch()` resolves `null` at end-of-stream; `cancel()` is idempotent
 * and wakes a pending `nextBatch` with `null`. Dropping the stream cancels
 * it (the underlying query subscription closes with it).
 */
export declare class QueryStream {
  /** Output schema of the query. */
  schema(): Array<FieldInfo>
  /** The query handle id (usable with `Connection.cancelQuery`). */
  queryId(): number
  /** Wait for the next batch; `null` at end-of-stream or after `cancel()`. */
  nextBatch(): Promise<ArrowBatch | null>
  /** Cancel the query (idempotent); a pending `nextBatch` resolves `null`. */
  cancel(): void
}

/**
 * A pull-based framed subscription to a named stream or materialized view.
 *
 * `nextFrame()` resolves one frame at a time (natural backpressure); `null`
 * means end-of-stream; terminal failures reject once (`LAMINAR_502` for
 * lag, `LAMINAR_500` otherwise) and end the subscription. `cancel()` is
 * idempotent and wakes a pending `nextFrame` with `null`.
 */
export declare class Subscription {
  /** Output schema of the subscribed object. */
  schema(): Array<FieldInfo>
  /**
   * Wait for the next frame; `null` on end-of-stream or after `cancel()`.
   * Terminal failures reject with `LAMINAR_502` (lag) or `LAMINAR_500`.
   */
  nextFrame(): Promise<SubscriptionFrame | null>
  isActive(): boolean
  /**
   * Stop the subscription (idempotent); a pending `nextFrame` resolves
   * `null`.
   */
  cancel(): void
}

/**
 * One frame from a subscription: `kind` is `'data'` (carries `batch`) or
 * `'barrier'` (checkpoint progress).
 */
export declare class SubscriptionFrame {
  /** `'data'` or `'barrier'`. */
  get kind(): string
  /** The data batch; `undefined` for barriers. */
  get batch(): ArrowBatch | null
  /** Portal-local delivery sequence (neither durable nor cluster-global). */
  get sequence(): number
  get epoch(): number | null
  get checkpointId(): number | null
  get throughSequence(): number | null
}

/**
 * Streaming writer for one source: single-owner, hot-path pushes.
 *
 * `writeRows`/`writeArrow` push batch-at-a-time into the engine; backpressure
 * is observable via `pending`/`capacity`/`isBackpressured`. `close()` is
 * idempotent; writes after close reject with `LAMINAR_301`.
 */
export declare class Writer {
  /** Source name. */
  name(): string
  /** Source schema fields. */
  schema(): Array<FieldInfo>
  /** Build from JS row objects and push one batch. */
  writeRows(rows: Array<object>): number
  /** Push every batch from an Arrow IPC stream `Buffer`. */
  writeArrow(bytes: Buffer): number
  /** Advance the event-time watermark (milliseconds since epoch). */
  watermark(timestamp: number): void
  /** Current event-time watermark. */
  currentWatermark(): number
  /** Rows buffered in the source, not yet consumed by the pipeline. */
  pending(): number
  /** Source buffer capacity in rows. */
  capacity(): number
  /** True when the source buffer is more than 80% full — slow down. */
  isBackpressured(): boolean
  /** Idempotent close; writes after close reject with `LAMINAR_301`. */
  close(): void
}

/**
 * The error payload for push-subscription `onError` callbacks. An object
 * rather than a spread pair: threadsafe calls deliver exactly one JS
 * argument per message.
 */
export interface CallbackError {
  /** Core error code (e.g. 500, 502). */
  code: number
  /** Message including the `[LAMINAR_<code>]` prefix. */
  message: string
}

/** Checkpointing options; an empty object enables manual checkpoints only. */
export interface CheckpointConfig {
  /** Interval in milliseconds; absent = manual `checkpoint()` calls only. */
  intervalMs?: number
  /**
   * One end-to-end attempt deadline in milliseconds; absent = core default
   * (120 s).
   */
  timeoutMs?: number
  /**
   * Checkpoint directory; absent = the database storage directory, then
   * `./data` (the core never silently selects volatile storage).
   */
  dataDir?: string
  /**
   * Maximum bytes for one participant's checkpoint node-data object;
   * absent = core default.
   */
  maxNodeDataBytes?: number
}

/** One manual checkpoint's outcome. */
export interface CheckpointOutcome {
  success: boolean
  checkpointId: number
  epoch: number
  durationMs: number
  /** Continuation error (present when successful checkpoints still recorded one). */
  error?: string
}

/**
 * One column of a result schema.
 *
 * `data_type` is the Arrow type string (Debug-formatted, like the core's FFI
 * layer reports it) — informational; parse it only for display.
 */
export interface FieldInfo {
  name: string
  dataType: string
  nullable: boolean
}

/**
 * Open an embedded database. `open()` and `open(':memory:')` are in-memory;
 * `open(path)` sets the storage directory (local-durable embedded mode when
 * checkpointing is configured); `config.storageDir` wins over the positional
 * path when both are given.
 */
export declare function open(path?: string | undefined | null, config?: OpenConfig | undefined | null): Promise<Connection>

/**
 * Connection options for `open`. `:memory:` (or no storage directory)
 * opens in-memory.
 */
export interface OpenConfig {
  /** Local durability directory. Wins over the positional path argument. */
  storageDir?: string
  checkpoint?: CheckpointConfig
  /** Default source buffer size in rows. */
  bufferSize?: number
  /** Emit windowed aggregates incrementally before window close. */
  incrementalEmit?: boolean
  /** Object-store URL for cloud checkpoints (e.g. `s3://bucket/prefix`). */
  objectStoreUrl?: string
  /** Object-store options (credentials, region, endpoint). */
  objectStoreOptions?: Record<string, string>
}

/** Aggregate pipeline counters. */
export interface PipelineMetricsObject {
  totalEventsIngested: number
  totalEventsEmitted: number
  totalEventsDropped: number
  totalCycles: number
  totalBatches: number
  uptimeMs: number
  /** Engine lifecycle state name (e.g. `Running`). */
  state: string
  sourceCount: number
  streamCount: number
  sinkCount: number
  /** Minimum watermark across all sources (epoch milliseconds). */
  pipelineWatermark: number
  mvUpdates: number
  mvBytesStored: number
}

/** One registered source: name, schema, watermark column. */
export interface SourceInfoObject {
  name: string
  schema: Array<FieldInfo>
  watermarkColumn?: string
}

/** Counters for one registered source. */
export interface SourceMetricsObject {
  name: string
  totalEvents: number
  pending: number
  capacity: number
  isBackpressured: boolean
  /** Event-time watermark (epoch milliseconds). */
  watermark: number
  /** Buffer utilization, 0.0..1.0. */
  utilization: number
}

/** Counters for one stream. */
export interface StreamMetricsObject {
  name: string
  totalEvents: number
  /** Defining SQL, when known. */
  sql?: string
}

/** Binding and pinned-core version, e.g. `"0.30.0-alpha.1 (core v0.30.0)"`. */
export declare function version(): string
