/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One Arrow `RecordBatch` of query output.
 *
 * Data leaves via `toIPC()` (one copy; rehydrate with `apache-arrow`'s
 * `tableFromIPC`) or `toArray()` (row objects). The batch is immutable.
 */
export declare class ArrowBatch {
  numRows(): number
  numColumns(): number
  schema(): Array<FieldInfo>
  /** This batch as an Arrow IPC stream `Buffer` (schema included). */
  toIPC(): Buffer
  /**
   * Row objects (one per row, keyed by column); see `conversion` for the
   * type conventions and the supported-type set.
   */
  toArray(): Array<object>
}

export declare class Connection {
  /**
   * Execute one SQL statement. `SELECT` returns `kind: "query"` with the
   * fully collected `result`; SHOW/DESCRIBE return `kind: "metadata"` with
   * their batch; DDL and `INSERT INTO` return their statement outcome.
   * Fails with `LAMINAR_101` after `close()`.
   */
  execute(sql: string): Promise<ExecuteOutcome>
  /**
   * Execute a query and return its fully collected result. Non-query SQL
   * rejects with `LAMINAR_400`.
   */
  query(sql: string): Promise<QueryResult>
  /**
   * Ingest JS row objects into a source (one batch; returns rows pushed).
   *
   * Sync by design: no engine await is involved (schema resolve → convert →
   * channel send) and the row conversion needs the JS `Env`, which is only
   * valid on the calling turn.
   */
  insert(source: string, rows: Array<object>): number
  /** Ingest an Arrow IPC stream `Buffer` into a source (all batches). */
  insertArrow(source: string, bytes: Buffer): number
  /**
   * Open a streaming writer for a source. Single-owner; writes after
   * `close()` reject with `LAMINAR_301`.
   */
  writer(source: string): Writer
  /** Start the streaming pipeline (idempotent). */
  start(): Promise<void>
  /**
   * Trigger a manual checkpoint. Rejects when checkpointing is not
   * configured (`checkpoint` in the open config), when no pipeline
   * topology exists (at least one stream or sink must be defined — the
   * core wires the coordinator only then), or when the attempt fails.
   */
  checkpoint(): Promise<CheckpointOutcome>
  /** True when checkpointing is configured for this connection. */
  isCheckpointEnabled(): boolean
  /** Registered source names. */
  listSources(): Promise<Array<string>>
  /** Registered stream names. */
  listStreams(): Promise<Array<string>>
  /** Registered sink names. */
  listSinks(): Promise<Array<string>>
  /** All registered sources with schemas and watermark columns. */
  sourceInfos(): Promise<Array<SourceInfoObject>>
  /** Schema of a source as field info; unknown names reject `LAMINAR_200`. */
  schema(name: string): Promise<Array<FieldInfo>>
  isClosed(): boolean
  /**
   * Close the connection: graceful engine shutdown, idempotent, and safe
   * under concurrent calls — the first caller performs the shutdown, later
   * calls are no-ops. Using the connection after `close()` fails with
   * `LAMINAR_101`. The core's shutdown has an internal 45 s deadline, so a
   * close can reject on timeout rather than hang forever.
   */
  close(): Promise<void>
}

/**
 * One executed statement's outcome, discriminated by the `kind` getter:
 * `ddl` | `rows-affected` | `query` | `metadata`.
 *
 * `query` and `metadata` outcomes carry the fully collected `result()`;
 * `ddl` and `rows-affected` carry their statement information.
 */
export declare class ExecuteOutcome {
  get kind(): string
  /** DDL statement type (e.g. `"CREATE SOURCE"`); `undefined` otherwise. */
  get statementType(): string | null
  /** DDL object name; `undefined` otherwise. */
  get objectName(): string | null
  get rowsAffected(): number | null
  get queryId(): number | null
  /**
   * The collected result for `query`/`metadata` outcomes; `undefined`
   * for `ddl`/`rows-affected`.
   */
  get result(): QueryResult | null
}

/** A fully collected query result: schema plus all output batches. */
export declare class QueryResult {
  schema(): Array<FieldInfo>
  numRows(): number
  numBatches(): number
  /** Batch `index` (0-based); rejects with 400 when out of range. */
  batch(index: number): ArrowBatch
  /** The whole result as one Arrow IPC stream `Buffer` (schema included). */
  toIPC(): Buffer
  /** All rows as objects, batch order preserved. */
  toArray(): Array<object>
}

/**
 * Streaming writer for one source: single-owner, hot-path pushes.
 *
 * `writeRows`/`writeArrow` push batch-at-a-time into the engine; backpressure
 * is observable via `pending`/`capacity`/`isBackpressured`. `close()` is
 * idempotent; writes after close reject with `LAMINAR_301`.
 */
export declare class Writer {
  /** Source name. */
  name(): string
  /** Source schema fields. */
  schema(): Array<FieldInfo>
  /** Build from JS row objects and push one batch. */
  writeRows(rows: Array<object>): number
  /** Push every batch from an Arrow IPC stream `Buffer`. */
  writeArrow(bytes: Buffer): number
  /** Advance the event-time watermark (milliseconds since epoch). */
  watermark(timestamp: number): void
  /** Current event-time watermark. */
  currentWatermark(): number
  /** Rows buffered in the source, not yet consumed by the pipeline. */
  pending(): number
  /** Source buffer capacity in rows. */
  capacity(): number
  /** True when the source buffer is more than 80% full — slow down. */
  isBackpressured(): boolean
  /** Idempotent close; writes after close reject with `LAMINAR_301`. */
  close(): void
}

/** Checkpointing options; an empty object enables manual checkpoints only. */
export interface CheckpointConfig {
  /** Interval in milliseconds; absent = manual `checkpoint()` calls only. */
  intervalMs?: number
  /**
   * One end-to-end attempt deadline in milliseconds; absent = core default
   * (120 s).
   */
  timeoutMs?: number
  /**
   * Checkpoint directory; absent = the database storage directory, then
   * `./data` (the core never silently selects volatile storage).
   */
  dataDir?: string
  /**
   * Maximum bytes for one participant's checkpoint node-data object;
   * absent = core default.
   */
  maxNodeDataBytes?: number
}

/** One manual checkpoint's outcome. */
export interface CheckpointOutcome {
  success: boolean
  checkpointId: number
  epoch: number
  durationMs: number
  /** Continuation error (present when successful checkpoints still recorded one). */
  error?: string
}

/**
 * One column of a result schema.
 *
 * `data_type` is the Arrow type string (Debug-formatted, like the core's FFI
 * layer reports it) — informational; parse it only for display.
 */
export interface FieldInfo {
  name: string
  dataType: string
  nullable: boolean
}

/**
 * Open an embedded database. `open()` and `open(':memory:')` are in-memory;
 * `open(path)` sets the storage directory (local-durable embedded mode when
 * checkpointing is configured); `config.storageDir` wins over the positional
 * path when both are given.
 */
export declare function open(path?: string | undefined | null, config?: OpenConfig | undefined | null): Promise<Connection>

/**
 * Connection options for `open`. `:memory:` (or no storage directory)
 * opens in-memory.
 */
export interface OpenConfig {
  /** Local durability directory. Wins over the positional path argument. */
  storageDir?: string
  checkpoint?: CheckpointConfig
  /** Default source buffer size in rows. */
  bufferSize?: number
  /** Emit windowed aggregates incrementally before window close. */
  incrementalEmit?: boolean
  /** Object-store URL for cloud checkpoints (e.g. `s3://bucket/prefix`). */
  objectStoreUrl?: string
  /** Object-store options (credentials, region, endpoint). */
  objectStoreOptions?: Record<string, string>
}

/** One registered source: name, schema, watermark column. */
export interface SourceInfoObject {
  name: string
  schema: Array<FieldInfo>
  watermarkColumn?: string
}

/** Binding and pinned-core version, e.g. `"0.30.0-alpha.1 (core v0.30.0)"`. */
export declare function version(): string
