/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Connection {
  /**
   * Execute one SQL statement. DDL and `INSERT INTO` return their outcome
   * directly; a `SELECT` returns `kind: "query"` (results via `query()`,
   * Phase 1). Fails with `LAMINAR_101` after `close()`.
   */
  execute(sql: string): Promise<ExecuteOutcome>
  isClosed(): boolean
  /**
   * Close the connection: graceful engine shutdown, idempotent, and safe
   * under concurrent calls — the first caller performs the shutdown, later
   * calls are no-ops. Using the connection after `close()` fails with
   * `LAMINAR_101`. The core's shutdown has an internal 45 s deadline, so a
   * close can reject on timeout rather than hang forever.
   */
  close(): Promise<void>
}

/**
 * One executed statement's outcome, discriminated by `kind`:
 * `ddl` | `rows-affected` | `query` | `metadata`.
 *
 * Phase 0 drops the payload for `query` and `metadata` results (collected
 * rows arrive with `query()` in Phase 1); `ddl` and `rows-affected` carry
 * their full information.
 */
export interface ExecuteOutcome {
  kind: string
  statementType?: string
  objectName?: string
  rowsAffected?: number
  queryId?: number
}

/**
 * Open an in-memory embedded database with core-default configuration.
 *
 * Phase 0 opens with defaults only; `openWithConfig` (storage directory,
 * checkpoint options) arrives in Phase 1 (plan 02 §2).
 */
export declare function open(): Promise<Connection>

/** Binding and pinned-core version, e.g. `"0.30.0-alpha.1 (core v0.30.0)"`. */
export declare function version(): string
